### ISSUE TITLE
再通知機能がほしい

### ISSUE THREAD

**Issue by tksugimoto** [tksugimoto/chrome-extension_ariel-schedule-notifier#4]
例えば、「5分後に再通知」ボタンを通知に追加する

**Comment by sambatriste** [comment]
「5分前だな、近くの会議室だから1分前に移動しよう」と思いながら作業して遅れることがあるので、
再通知機能があるとありがたいです。

**Comment by tksugimoto** [comment]
実装 (#11) してリリースしました。
そのうち自動アップデートされると思います。

※ 現在 1分前 再通知固定です

**Comment by sambatriste** [comment]
いつのまにか再通知できるようになっていました！
